name: Maven Build, Docker Image, and Postman Tests

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Set up JDK 21 Corretto
      - name: Set up JDK 21 (Corretto)
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      # Run Maven Build
      - name: Run Maven Build
        run: mvn clean package

      # Upload the target directory as an artifact
      - name: Upload Maven Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: maven-build
          path: target/

  test:
    runs-on: ubuntu-24.04
    needs: build

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Download Maven Build Artifacts
      - name: Download Maven Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: maven-build
          path: target/

      # Build Docker Image
      - name: Build Docker Image
        run: docker build -t customer-management-api .

      # Create a Docker Network
      - name: Create Docker Network
        run: docker network create test-network

      # Start the App Container
      - name: Start App Container
        run: |
          docker run -d --name app --network test-network \
            -p 8080:8080 customer-management-api
          sleep 10  # Allow the app to start

      # Run Postman Tests with Newman
      - name: Run Postman Tests
        run: |
          docker run --rm --network test-network \
            -v $(pwd)/postman:/etc/newman dannydainton/htmlextra \
            run /etc/newman/acceptance_tests.postman_collection.json \
            --reporters cli,htmlextra \
            --reporter-htmlextra-export /etc/newman/reports/report.html \
            --env-var base_url=http://app:8080

      # Upload Postman Test Report as Artifact
      - name: Upload Postman Test Report
        uses: actions/upload-artifact@v4
        with:
          name: postman-test-report
          path: postman/reports/report.html

      # Clean up Docker Network and Containers
      - name: Clean Up
        run: |
          docker stop app
          docker network rm test-network
