name: Maven Build and Docker Compose

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Set up JDK 21 Corretto
      - name: Set up JDK 21 (Corretto)
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      # Set up Maven caching for faster builds
      - name: Cache Maven Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: maven-

      # Run Maven Build
      - name: Run Maven Build
        run: mvn clean package

      # Build Docker Image
      - name: Build Docker Image
        run: docker build -t customer-management-api .

      # Run Docker Compose Services
      - name: Start Services with Docker Compose
        run: docker-compose up -d

      # Stop and Clean Up Docker Compose
      - name: Stop Docker Compose Services
        run: docker-compose down
